title: Gorepoint
email: info@gorepoint.com
description: Gorepoint Internet Services & Consulting
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
